services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/appdb
      CORS_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173"
      # Allow any http(s)://<ip-or-hostname> with optional port (for Vite on different ports)
      CORS_ORIGIN_REGEX: '^https?://[a-zA-Z0-9_.-]+(?::\d+)?$'
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
